
export const comments=[
    {vid:1,name:"Abas",comment: "great video"},
    {vid:2,name:"Willson",comment: "nice video!"},
    {vid:1,name:"Ahmed",comment: "great video"},
    {vid:3,name:"XYZ",comment: "Awesome"},
    {vid:1,name:"Abas",comment: "Officially the first viewer of any video on this channel. "},
    {vid:1,name:"Liam",comment: "great video"},
    {vid:4,name:"Elijah",comment: "You're an awesome friend."},
    {vid:1,name:"Oliver",comment: "I truly love your channel. Keep doing the best work. "},
    {vid:2,name:"James",comment: "Such creative videos you’ve on this channel. Just subscribed!"},
    {vid:1,name:"Jennifer",comment: "I’ve never witnessed such awesome editing as this one. "},
    {vid:4,name:"Linda",comment: "Congratulations on your first 10K followers, may you reach 100K soon. "},
    {vid:1,name:"Michael",comment: "Whoever is reading this, never give up. God is with you. "},
    {vid:2,name:"William",comment: "When watching your videos, I accidentally hit ‘like’ and never knew when. "},
    {vid:4,name:"Richard",comment: "The moment you came here is at 05:17. "},
    {vid:5,name:"Barbara",comment: "great video"}, 
    {vid:6,name:"Liam",comment: "great video"},
    {vid:5,name:"Elijah",comment: "You're an awesome friend."},
    {vid:4,name:"Oliver",comment: "I truly love your channel. Keep doing the best work. "},
    {vid:7,name:"James",comment: "Such creative videos you’ve on this channel. Just subscribed!"},
    {vid:6,name:"Jennifer",comment: "I’ve never witnessed such awesome editing as this one. "},
    {vid:5,name:"Linda",comment: "Congratulations on your first 10K followers, may you reach 100K soon. "},
    {vid:7,name:"Michael",comment: "Whoever is reading this, never give up. God is with you. "},
    {vid:8,name:"William",comment: "When watching your videos, I accidentally hit ‘like’ and never knew when. "},
    {vid:9,name:"Richard",comment: "The moment you came here is at 05:17. "},
    {vid:8,name:"Barbara",comment: "great video"},
    {vid:8,name:"Abas",comment: "great video"},
    {vid:9,name:"Willson",comment: "nice video!"},
    {vid:10,name:"Ahmed",comment: "great video"},
    {vid:11,name:"XYZ",comment: "Awesome"},
    {vid:10,name:"Abas",comment: "Officially the first viewer of any video on this channel. "},
    {vid:11,name:"Liam",comment: "great video"},
    {vid:7,name:"James",comment: "Such creative videos you’ve on this channel. Just subscribed!"},
    {vid:11,name:"Jennifer",comment: "I’ve never witnessed such awesome editing as this one. "},
    {vid:10,name:"Linda",comment: "Congratulations on your first 10K followers, may you reach 100K soon. "},
    {vid:12,name:"Michael",comment: "Whoever is reading this, never give up. God is with you. "},
    {vid:13,name:"William",comment: "When watching your videos, I accidentally hit ‘like’ and never knew when. "},
    {vid:12,name:"Richard",comment: "The moment you came here is at 05:17. "},
    {vid:14,name:"Barbara",comment: "great video"},
    {vid:13,name:"Abas",comment: "great video"},
    {vid:14,name:"Willson",comment: "nice video!"},
    {vid:15,name:"Ahmed",comment: "great video"},
    {vid:14,name:"XYZ",comment: "Awesome"},
    {vid:15,name:"Abas",comment: "Officially the first viewer of any video on this channel. "},
    {vid:16,name:"Liam",comment: "great video"},
    {vid:16,name:"James",comment: "Such creative videos you’ve on this channel. Just subscribed!"},
    {vid:15,name:"Jennifer",comment: "I’ve never witnessed such awesome editing as this one. "},
    {vid:14,name:"Linda",comment: "Congratulations on your first 10K followers, may you reach 100K soon. "},
    {vid:17,name:"Michael",comment: "Whoever is reading this, never give up. God is with you. "},
    {vid:16,name:"William",comment: "When watching your videos, I accidentally hit ‘like’ and never knew when. "},
    {vid:18,name:"Richard",comment: "The moment you came here is at 05:17. "},
    {vid:17,name:"Barbara",comment: "great video"},
    {vid:20,name:"Abas",comment: "great video"},
    {vid:18,name:"Willson",comment: "nice video!"},
    {vid:19,name:"Ahmed",comment: "great video"},
    {vid:21,name:"XYZ",comment: "Awesome"},
    {vid:20,name:"Abas",comment: "Officially the first viewer of any video on this channel. "},
    {vid:21,name:"Liam",comment: "great video"},
]